apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: web-application
  namespace: '260521'
spec:
  schema:
    apiVersion: v1alpha1
    kind: WebApplication
    spec:
      name: string
      image: string | default="nginx:1.25"
      replicas: integer | default=3
    status:
      bucketArn: ${bucket.status.ackResourceMetadata.arn}
      ready: ${deployment.status.?readyReplicas.orValue(0) > 0}
  resources:
    # Create {aws} S3 bucket with ACK
    - id: bucket
      template:
        apiVersion: s3.services.k8s.aws/v1alpha1
        kind: Bucket
        metadata:
          name: ${schema.spec.name}-assets
          annotations:
            services.k8s.aws/deletion-policy: retain
        spec:
          name: ${schema.spec.name}-assets
    # Inject bucket details into Kubernetes ConfigMap
    - id: configmap 
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ${schema.spec.name}-configmap
        data:
          BUCKET_NAME: ${bucket.spec.name}
          BUCKET_ARN: ${bucket.status.ackResourceMetadata.arn}
    # Use ConfigMap in application deployment
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name}
        spec:
          replicas: ${schema.spec.replicas}
          selector:
            matchLabels:
              app: ${schema.spec.name}
          template:
            metadata:
              labels:
                app: ${schema.spec.name}
            spec:
              containers:
                - name: app
                  image: ${schema.spec.image}
                  envFrom:
                  - configMapRef:
                      name: ${configmap.metadata.name}
                  # env:
                  #   - name: BUCKET_ARN
                  #     value: ${bucket.status.ackResourceMetadata.arn}
    # Expose the application via Service
    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${schema.spec.name}
        spec:
          selector:
            app: ${schema.spec.name}
          ports:
            - port: 80
              targetPort: 80